### ISSUE TITLE
Extra docs on exactly where to start installing things?

### ISSUE THREAD

**Issue by jywarren** [publiclab/pi-builder#36]
I see this line is where some PRs start to make changes:

https://github.com/publiclab/pi-builder/blob/f9481e45f189ba1e7b15c6a6c2dd364b31540547/builder/chroot-script.sh#L207

Should we put some comment there and delineate an area where it's ideal to start installing scripts and running `git` or `npm`? I assume git is installed, is npm too? 

Thank you!

**Comment by jywarren** [comment]
Looking at #37 to install some NPM stuff...

**Comment by jywarren** [comment]
Aha, sorry, so i think we need to separately document where to put things on initial install, vs. on each startup. 

Maybe we ought to actually make 2 files, called `startup` and `setup`, which would be run as root? Then just link to them from the appropriate places? But i'm open to whatever makes sense!

**Comment by icarito** [comment]
We have two scripts, one runs _outside_ the chroot as the build system (build.sh) and the other inside chroot (chroot-script.sh). Both run as root. The appropriate place to install git and npm etc is `chroot-script.sh`.

**Comment by jywarren** [comment]
OK, and the place to put things to run on boot would be in a crontab,
potentially? Thanks!

**Comment by icarito** [comment]
Oh, yes, I should add these questions to the docs. The canonical way to run stuff on boot is to add them to `/etc/rc.local`.

**Comment by icarito** [comment]
In the Camera PR I had to add an empty rc.local because the install script will modify it https://github.com/publiclab/pi-builder/pull/13/files#diff-25aa350b8efc5496496765f60725aa9c 
Also this is documented at https://publiclab.gitlab.io/pi-builder/scripting.html#running-scripts-on-startup

**Comment by icarito** [comment]
The general architecture is that files under `/builder/files` get copied over to the final image (before chroot script is run).

**Comment by jywarren** [comment]
awesome, thanks!!!
